"""empty message

Revision ID: 1079c7c70ce9
Revises: 678304bd5a2e
Create Date: 2024-12-17 18:58:16.532025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1079c7c70ce9'
down_revision = '678304bd5a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('shared_with')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shared_with_you')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_you', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sqlite.JSON(), nullable=True))

    op.drop_table('shared_note')
    # ### end Alembic commands ###
