"""empty message

Revision ID: 25a4dd3b7bf8
Revises: aabbdc5146c5
Create Date: 2024-12-18 12:39:02.317474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4dd3b7bf8'
down_revision = 'aabbdc5146c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###
