"""empty message

Revision ID: 678304bd5a2e
Revises: ea4403a2a300
Create Date: 2024-12-16 21:45:01.167295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678304bd5a2e'
down_revision = 'ea4403a2a300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_you', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shared_with_you')

    # ### end Alembic commands ###
