"""empty message

Revision ID: aabbdc5146c5
Revises: e7f1a946a65b
Create Date: 2024-12-17 23:43:12.187127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabbdc5146c5'
down_revision = 'e7f1a946a65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_code_expiry')
        batch_op.drop_column('registration_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_code', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('registration_code_expiry', sa.DATETIME(), nullable=True))

    op.drop_table('verification_code')
    # ### end Alembic commands ###
