"""empty message

Revision ID: e7f1a946a65b
Revises: 1079c7c70ce9
Create Date: 2024-12-17 22:36:30.053355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f1a946a65b'
down_revision = '1079c7c70ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('registration_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('registration_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_code_expiry')
        batch_op.drop_column('registration_code')
        batch_op.drop_column('reset_code_expiry')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
